[package]
name = "nvim_switcher"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
flate2 = "1.0.34"
tar = "0.4.43"
